// domains/ui/index.js
// Phase 5: UI layer exports

export const UIRenderers = {
    closeAchievements,
    closeAlchemy,
    closeBeyondHeaven,
    closeBeyondResult,
    closeCelestialEconomy,
    closeCombat,
    closeDiscipleSelectionModal,
    closeEnhancePanel,
    closeEquipSlotMenu,
    closeEvolutionUI,
    closeGiftMenu,
    closeHeavenlyDaoSlotMenu,
    closeInventory,
    closeModal,
    closeNpcDialogue,
    closePalace,
    closePet,
    closeRankingPVP,
    closeSect,
    closeSerendipityModal,
    closeSettings,
    closeShop,
    closeSpiritRootModal,
    closeTechniqueUpgradeModal,
    closeWorldMap,
    openAchievements,
    openAlchemy,
    openBeyondHeaven,
    openCelestialEconomy,
    openCombat,
    openCrafting,
    openEnhanceFromEquip,
    openEnhanceFromInventory,
    openEnhancePanel,
    openEquipSlotMenu,
    openEvolutionUI,
    openForge,
    openHeavenlyDaoSlotMenu,
    openInventory,
    openMarket,
    openModal,
    openNpcDialogue,
    openPalace,
    openPet,
    openRankingPVP,
    openSect,
    openSerendipityLog,
    openSettings,
    openShop,
    openSpiritRootModal,
    openTechniqueUpgrade,
    openWorldMap,
    renderAchievements,
    renderBeyondHeaven,
    renderBuildingsTab,
    renderCelestialEconomy,
    renderCelestialInvestTab,
    renderCelestialMarketTab,
    renderChallengeTab,
    renderCombatArena,
    renderCombatHome,
    renderCombatResult,
    renderContributionShop,
    renderCounterEnergyBar,
    renderCraftingRecipes,
    renderCreatePalaceForm,
    renderCreateSectForm,
    renderDaoAncestor,
    renderDisciplesTab,
    renderHeavenlyDaoSetStatus,
    renderHistoryTab,
    renderInventoryGrid,
    renderLog,
    renderManageTab,
    renderMarketItems,
    renderMyPets,
    renderPalaceDisciplesTab,
    renderPalaceHome,
    renderPalaceManageTab,
    renderPalaceSectDualTrack,
    renderPalaceTasksTab,
    renderPetBreeding,
    renderPetFusion,
    renderPetHome,
    renderPetIncubation,
    renderPetMarket,
    renderPlayerActions,
    renderRankingPVP,
    renderRankingTab,
    renderRegionDetail,
    renderRoomsTab,
    renderSeasonTab,
    renderSectHome,
    renderSectPalaceDualTrack,
    renderSetStatus,
    renderShopItems,
    renderSpiritRootContent,
    renderSummonPet,
    renderTechniquesTab,
    renderThirtyThreeHeavens,
    renderUltimateEnergyBar,
    renderWorldMap,
};

// Re-export all renderer modules
export * from './renderers/achievement.js';
export * from './renderers/combat.js';
export * from './renderers/inventory.js';
export * from './renderers/shop.js';
export * from './renderers/pet.js';
export * from './renderers/sect.js';
export * from './renderers/world.js';
export * from './renderers/celestial.js';
export * from './renderers/modal.js';
export * from './renderers/log.js';
